<?php
/**
 * NfeSefazCredPresOper
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  NuvemFiscal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Nuvem Fiscal
 *
 * API para automação comercial e documentos fiscais.
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.7.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace NuvemFiscal\Model;

use \ArrayAccess;
use \NuvemFiscal\ObjectSerializer;

/**
 * NfeSefazCredPresOper Class Doc Comment
 *
 * @category Class
 * @description Crédito Presumido da Operação. Informado conforme indicador no cClassTrib.
 * @package  NuvemFiscal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class NfeSefazCredPresOper implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'NfeSefazCredPresOper';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'v_bc_cred_pres' => 'float',
        'c_cred_pres' => 'string',
        'g_ibs_cred_pres' => '\NuvemFiscal\Model\NfeSefazCredPres',
        'g_cbs_cred_pres' => '\NuvemFiscal\Model\NfeSefazCredPres'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'v_bc_cred_pres' => null,
        'c_cred_pres' => null,
        'g_ibs_cred_pres' => null,
        'g_cbs_cred_pres' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'v_bc_cred_pres' => true,
        'c_cred_pres' => true,
        'g_ibs_cred_pres' => false,
        'g_cbs_cred_pres' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'v_bc_cred_pres' => 'vBCCredPres',
        'c_cred_pres' => 'cCredPres',
        'g_ibs_cred_pres' => 'gIBSCredPres',
        'g_cbs_cred_pres' => 'gCBSCredPres'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'v_bc_cred_pres' => 'setVBcCredPres',
        'c_cred_pres' => 'setCCredPres',
        'g_ibs_cred_pres' => 'setGIbsCredPres',
        'g_cbs_cred_pres' => 'setGCbsCredPres'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'v_bc_cred_pres' => 'getVBcCredPres',
        'c_cred_pres' => 'getCCredPres',
        'g_ibs_cred_pres' => 'getGIbsCredPres',
        'g_cbs_cred_pres' => 'getGCbsCredPres'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('v_bc_cred_pres', $data ?? [], null);
        $this->setIfExists('c_cred_pres', $data ?? [], null);
        $this->setIfExists('g_ibs_cred_pres', $data ?? [], null);
        $this->setIfExists('g_cbs_cred_pres', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['v_bc_cred_pres'] === null) {
            $invalidProperties[] = "'v_bc_cred_pres' can't be null";
        }
        if (($this->container['v_bc_cred_pres'] < 0)) {
            $invalidProperties[] = "invalid value for 'v_bc_cred_pres', must be bigger than or equal to 0.";
        }

        if ($this->container['c_cred_pres'] === null) {
            $invalidProperties[] = "'c_cred_pres' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets v_bc_cred_pres
     *
     * @return float
     */
    public function getVBcCredPres()
    {
        return $this->container['v_bc_cred_pres'];
    }

    /**
     * Sets v_bc_cred_pres
     *
     * @param float $v_bc_cred_pres Valor da Base de Cálculo do Crédito Presumido da Operação.
     *
     * @return self
     */
    public function setVBcCredPres($v_bc_cred_pres)
    {
        if (is_null($v_bc_cred_pres)) {
            array_push($this->openAPINullablesSetToNull, 'v_bc_cred_pres');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('v_bc_cred_pres', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($v_bc_cred_pres) && ($v_bc_cred_pres < 0)) {
            throw new \InvalidArgumentException('invalid value for $v_bc_cred_pres when calling NfeSefazCredPresOper., must be bigger than or equal to 0.');
        }

        $this->container['v_bc_cred_pres'] = $v_bc_cred_pres;

        return $this;
    }

    /**
     * Gets c_cred_pres
     *
     * @return string
     */
    public function getCCredPres()
    {
        return $this->container['c_cred_pres'];
    }

    /**
     * Sets c_cred_pres
     *
     * @param string $c_cred_pres Código de Classificação do Crédito Presumido do IBS e da CBS.
     *
     * @return self
     */
    public function setCCredPres($c_cred_pres)
    {
        if (is_null($c_cred_pres)) {
            array_push($this->openAPINullablesSetToNull, 'c_cred_pres');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('c_cred_pres', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['c_cred_pres'] = $c_cred_pres;

        return $this;
    }

    /**
     * Gets g_ibs_cred_pres
     *
     * @return \NuvemFiscal\Model\NfeSefazCredPres|null
     */
    public function getGIbsCredPres()
    {
        return $this->container['g_ibs_cred_pres'];
    }

    /**
     * Sets g_ibs_cred_pres
     *
     * @param \NuvemFiscal\Model\NfeSefazCredPres|null $g_ibs_cred_pres g_ibs_cred_pres
     *
     * @return self
     */
    public function setGIbsCredPres($g_ibs_cred_pres)
    {
        if (is_null($g_ibs_cred_pres)) {
            throw new \InvalidArgumentException('non-nullable g_ibs_cred_pres cannot be null');
        }
        $this->container['g_ibs_cred_pres'] = $g_ibs_cred_pres;

        return $this;
    }

    /**
     * Gets g_cbs_cred_pres
     *
     * @return \NuvemFiscal\Model\NfeSefazCredPres|null
     */
    public function getGCbsCredPres()
    {
        return $this->container['g_cbs_cred_pres'];
    }

    /**
     * Sets g_cbs_cred_pres
     *
     * @param \NuvemFiscal\Model\NfeSefazCredPres|null $g_cbs_cred_pres g_cbs_cred_pres
     *
     * @return self
     */
    public function setGCbsCredPres($g_cbs_cred_pres)
    {
        if (is_null($g_cbs_cred_pres)) {
            throw new \InvalidArgumentException('non-nullable g_cbs_cred_pres cannot be null');
        }
        $this->container['g_cbs_cred_pres'] = $g_cbs_cred_pres;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


