<?php
/**
 * RTCInfoIBSCBS
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  NuvemFiscal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Nuvem Fiscal
 *
 * API para automação comercial e documentos fiscais.
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.7.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace NuvemFiscal\Model;

use \ArrayAccess;
use \NuvemFiscal\ObjectSerializer;

/**
 * RTCInfoIBSCBS Class Doc Comment
 *
 * @category Class
 * @description Grupo de informações declaradas pelo emitente referentes ao IBS e à CBS.
 * @package  NuvemFiscal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RTCInfoIBSCBS implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'RTCInfoIBSCBS';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'fin_nfse' => 'int',
        'ind_final' => 'int',
        'c_ind_op' => 'string',
        'tp_oper' => 'int',
        'g_ref_nfse' => '\NuvemFiscal\Model\InfoRefNFSe',
        'tp_ente_gov' => 'int',
        'ind_dest' => 'int',
        'dest' => '\NuvemFiscal\Model\RTCInfoDest',
        'imovel' => '\NuvemFiscal\Model\RTCInfoImovel',
        'valores' => '\NuvemFiscal\Model\RTCInfoValoresIBSCBS'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'fin_nfse' => null,
        'ind_final' => null,
        'c_ind_op' => null,
        'tp_oper' => null,
        'g_ref_nfse' => null,
        'tp_ente_gov' => null,
        'ind_dest' => null,
        'dest' => null,
        'imovel' => null,
        'valores' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'fin_nfse' => true,
        'ind_final' => true,
        'c_ind_op' => true,
        'tp_oper' => true,
        'g_ref_nfse' => false,
        'tp_ente_gov' => true,
        'ind_dest' => true,
        'dest' => false,
        'imovel' => false,
        'valores' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'fin_nfse' => 'finNFSe',
        'ind_final' => 'indFinal',
        'c_ind_op' => 'cIndOp',
        'tp_oper' => 'tpOper',
        'g_ref_nfse' => 'gRefNFSe',
        'tp_ente_gov' => 'tpEnteGov',
        'ind_dest' => 'indDest',
        'dest' => 'dest',
        'imovel' => 'imovel',
        'valores' => 'valores'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'fin_nfse' => 'setFinNfse',
        'ind_final' => 'setIndFinal',
        'c_ind_op' => 'setCIndOp',
        'tp_oper' => 'setTpOper',
        'g_ref_nfse' => 'setGRefNfse',
        'tp_ente_gov' => 'setTpEnteGov',
        'ind_dest' => 'setIndDest',
        'dest' => 'setDest',
        'imovel' => 'setImovel',
        'valores' => 'setValores'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'fin_nfse' => 'getFinNfse',
        'ind_final' => 'getIndFinal',
        'c_ind_op' => 'getCIndOp',
        'tp_oper' => 'getTpOper',
        'g_ref_nfse' => 'getGRefNfse',
        'tp_ente_gov' => 'getTpEnteGov',
        'ind_dest' => 'getIndDest',
        'dest' => 'getDest',
        'imovel' => 'getImovel',
        'valores' => 'getValores'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('fin_nfse', $data ?? [], null);
        $this->setIfExists('ind_final', $data ?? [], null);
        $this->setIfExists('c_ind_op', $data ?? [], null);
        $this->setIfExists('tp_oper', $data ?? [], null);
        $this->setIfExists('g_ref_nfse', $data ?? [], null);
        $this->setIfExists('tp_ente_gov', $data ?? [], null);
        $this->setIfExists('ind_dest', $data ?? [], null);
        $this->setIfExists('dest', $data ?? [], null);
        $this->setIfExists('imovel', $data ?? [], null);
        $this->setIfExists('valores', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['fin_nfse'] === null) {
            $invalidProperties[] = "'fin_nfse' can't be null";
        }
        if ($this->container['ind_final'] === null) {
            $invalidProperties[] = "'ind_final' can't be null";
        }
        if ($this->container['c_ind_op'] === null) {
            $invalidProperties[] = "'c_ind_op' can't be null";
        }
        if ($this->container['ind_dest'] === null) {
            $invalidProperties[] = "'ind_dest' can't be null";
        }
        if ($this->container['valores'] === null) {
            $invalidProperties[] = "'valores' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets fin_nfse
     *
     * @return int
     */
    public function getFinNfse()
    {
        return $this->container['fin_nfse'];
    }

    /**
     * Sets fin_nfse
     *
     * @param int $fin_nfse Indicador da finalidade da emissão de NFS-e:  * 0 - NFS-e regular.
     *
     * @return self
     */
    public function setFinNfse($fin_nfse)
    {
        if (is_null($fin_nfse)) {
            array_push($this->openAPINullablesSetToNull, 'fin_nfse');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('fin_nfse', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['fin_nfse'] = $fin_nfse;

        return $this;
    }

    /**
     * Gets ind_final
     *
     * @return int
     */
    public function getIndFinal()
    {
        return $this->container['ind_final'];
    }

    /**
     * Sets ind_final
     *
     * @param int $ind_final Indica operação de uso ou consumo pessoal (art. 57):  * 0 - Não;  * 1 - Sim.
     *
     * @return self
     */
    public function setIndFinal($ind_final)
    {
        if (is_null($ind_final)) {
            array_push($this->openAPINullablesSetToNull, 'ind_final');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ind_final', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['ind_final'] = $ind_final;

        return $this;
    }

    /**
     * Gets c_ind_op
     *
     * @return string
     */
    public function getCIndOp()
    {
        return $this->container['c_ind_op'];
    }

    /**
     * Sets c_ind_op
     *
     * @param string $c_ind_op Código indicador da operação de fornecimento, conforme tabela \"código indicador de operação\".
     *
     * @return self
     */
    public function setCIndOp($c_ind_op)
    {
        if (is_null($c_ind_op)) {
            array_push($this->openAPINullablesSetToNull, 'c_ind_op');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('c_ind_op', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['c_ind_op'] = $c_ind_op;

        return $this;
    }

    /**
     * Gets tp_oper
     *
     * @return int|null
     */
    public function getTpOper()
    {
        return $this->container['tp_oper'];
    }

    /**
     * Sets tp_oper
     *
     * @param int|null $tp_oper Tipo de Operação com Entes Governamentais ou outros serviços sobre bens imóveis:  * 1 – Fornecimento com pagamento posterior;  * 2 - Recebimento do pagamento com fornecimento já realizado;  * 3 – Fornecimento com pagamento já realizado;  * 4 – Recebimento do pagamento com fornecimento posterior;  * 5 – Fornecimento e recebimento do pagamento concomitantes.
     *
     * @return self
     */
    public function setTpOper($tp_oper)
    {
        if (is_null($tp_oper)) {
            array_push($this->openAPINullablesSetToNull, 'tp_oper');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('tp_oper', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['tp_oper'] = $tp_oper;

        return $this;
    }

    /**
     * Gets g_ref_nfse
     *
     * @return \NuvemFiscal\Model\InfoRefNFSe|null
     */
    public function getGRefNfse()
    {
        return $this->container['g_ref_nfse'];
    }

    /**
     * Sets g_ref_nfse
     *
     * @param \NuvemFiscal\Model\InfoRefNFSe|null $g_ref_nfse g_ref_nfse
     *
     * @return self
     */
    public function setGRefNfse($g_ref_nfse)
    {
        if (is_null($g_ref_nfse)) {
            throw new \InvalidArgumentException('non-nullable g_ref_nfse cannot be null');
        }
        $this->container['g_ref_nfse'] = $g_ref_nfse;

        return $this;
    }

    /**
     * Gets tp_ente_gov
     *
     * @return int|null
     */
    public function getTpEnteGov()
    {
        return $this->container['tp_ente_gov'];
    }

    /**
     * Sets tp_ente_gov
     *
     * @param int|null $tp_ente_gov Tipo de ente governamental  Para administração pública direta e suas autarquias e fundações:  * 1 - União;  * 2 - Estado;  * 3 - Distrito Federal;  * 4 - Município.
     *
     * @return self
     */
    public function setTpEnteGov($tp_ente_gov)
    {
        if (is_null($tp_ente_gov)) {
            array_push($this->openAPINullablesSetToNull, 'tp_ente_gov');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('tp_ente_gov', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['tp_ente_gov'] = $tp_ente_gov;

        return $this;
    }

    /**
     * Gets ind_dest
     *
     * @return int
     */
    public function getIndDest()
    {
        return $this->container['ind_dest'];
    }

    /**
     * Sets ind_dest
     *
     * @param int $ind_dest A respeito do Destinatário dos serviços:  * 0 – O destinatário é o próprio tomador/adquirente identificado na NFS-e (tomador = adquirente = destinatário);  * 1 – O destinatário não é o próprio adquirente, podendo ser outra pessoa, física ou jurídica (ou equiparada), ou um estabelecimento diferente do indicado como tomador (tomador = adquirente != destinatário).
     *
     * @return self
     */
    public function setIndDest($ind_dest)
    {
        if (is_null($ind_dest)) {
            array_push($this->openAPINullablesSetToNull, 'ind_dest');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ind_dest', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['ind_dest'] = $ind_dest;

        return $this;
    }

    /**
     * Gets dest
     *
     * @return \NuvemFiscal\Model\RTCInfoDest|null
     */
    public function getDest()
    {
        return $this->container['dest'];
    }

    /**
     * Sets dest
     *
     * @param \NuvemFiscal\Model\RTCInfoDest|null $dest dest
     *
     * @return self
     */
    public function setDest($dest)
    {
        if (is_null($dest)) {
            throw new \InvalidArgumentException('non-nullable dest cannot be null');
        }
        $this->container['dest'] = $dest;

        return $this;
    }

    /**
     * Gets imovel
     *
     * @return \NuvemFiscal\Model\RTCInfoImovel|null
     */
    public function getImovel()
    {
        return $this->container['imovel'];
    }

    /**
     * Sets imovel
     *
     * @param \NuvemFiscal\Model\RTCInfoImovel|null $imovel imovel
     *
     * @return self
     */
    public function setImovel($imovel)
    {
        if (is_null($imovel)) {
            throw new \InvalidArgumentException('non-nullable imovel cannot be null');
        }
        $this->container['imovel'] = $imovel;

        return $this;
    }

    /**
     * Gets valores
     *
     * @return \NuvemFiscal\Model\RTCInfoValoresIBSCBS
     */
    public function getValores()
    {
        return $this->container['valores'];
    }

    /**
     * Sets valores
     *
     * @param \NuvemFiscal\Model\RTCInfoValoresIBSCBS $valores valores
     *
     * @return self
     */
    public function setValores($valores)
    {
        if (is_null($valores)) {
            throw new \InvalidArgumentException('non-nullable valores cannot be null');
        }
        $this->container['valores'] = $valores;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


