<?php
/**
 * RTCInfoTributosDif
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  NuvemFiscal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Nuvem Fiscal
 *
 * API para automação comercial e documentos fiscais.
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.7.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace NuvemFiscal\Model;

use \ArrayAccess;
use \NuvemFiscal\ObjectSerializer;

/**
 * RTCInfoTributosDif Class Doc Comment
 *
 * @category Class
 * @description Grupo de informações relacionadas ao diferimento para IBS e CBS.
 * @package  NuvemFiscal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RTCInfoTributosDif implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'RTCInfoTributosDif';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'p_dif_uf' => 'float',
        'p_dif_mun' => 'float',
        'p_dif_cbs' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'p_dif_uf' => null,
        'p_dif_mun' => null,
        'p_dif_cbs' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'p_dif_uf' => true,
        'p_dif_mun' => true,
        'p_dif_cbs' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'p_dif_uf' => 'pDifUF',
        'p_dif_mun' => 'pDifMun',
        'p_dif_cbs' => 'pDifCBS'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'p_dif_uf' => 'setPDifUf',
        'p_dif_mun' => 'setPDifMun',
        'p_dif_cbs' => 'setPDifCbs'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'p_dif_uf' => 'getPDifUf',
        'p_dif_mun' => 'getPDifMun',
        'p_dif_cbs' => 'getPDifCbs'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('p_dif_uf', $data ?? [], null);
        $this->setIfExists('p_dif_mun', $data ?? [], null);
        $this->setIfExists('p_dif_cbs', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['p_dif_uf'] === null) {
            $invalidProperties[] = "'p_dif_uf' can't be null";
        }
        if (($this->container['p_dif_uf'] < 0)) {
            $invalidProperties[] = "invalid value for 'p_dif_uf', must be bigger than or equal to 0.";
        }

        if ($this->container['p_dif_mun'] === null) {
            $invalidProperties[] = "'p_dif_mun' can't be null";
        }
        if (($this->container['p_dif_mun'] < 0)) {
            $invalidProperties[] = "invalid value for 'p_dif_mun', must be bigger than or equal to 0.";
        }

        if ($this->container['p_dif_cbs'] === null) {
            $invalidProperties[] = "'p_dif_cbs' can't be null";
        }
        if (($this->container['p_dif_cbs'] < 0)) {
            $invalidProperties[] = "invalid value for 'p_dif_cbs', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets p_dif_uf
     *
     * @return float
     */
    public function getPDifUf()
    {
        return $this->container['p_dif_uf'];
    }

    /**
     * Sets p_dif_uf
     *
     * @param float $p_dif_uf Percentual de diferimento para o IBS estadual.
     *
     * @return self
     */
    public function setPDifUf($p_dif_uf)
    {
        if (is_null($p_dif_uf)) {
            array_push($this->openAPINullablesSetToNull, 'p_dif_uf');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('p_dif_uf', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($p_dif_uf) && ($p_dif_uf < 0)) {
            throw new \InvalidArgumentException('invalid value for $p_dif_uf when calling RTCInfoTributosDif., must be bigger than or equal to 0.');
        }

        $this->container['p_dif_uf'] = $p_dif_uf;

        return $this;
    }

    /**
     * Gets p_dif_mun
     *
     * @return float
     */
    public function getPDifMun()
    {
        return $this->container['p_dif_mun'];
    }

    /**
     * Sets p_dif_mun
     *
     * @param float $p_dif_mun Percentual de diferimento para o IBS municipal.
     *
     * @return self
     */
    public function setPDifMun($p_dif_mun)
    {
        if (is_null($p_dif_mun)) {
            array_push($this->openAPINullablesSetToNull, 'p_dif_mun');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('p_dif_mun', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($p_dif_mun) && ($p_dif_mun < 0)) {
            throw new \InvalidArgumentException('invalid value for $p_dif_mun when calling RTCInfoTributosDif., must be bigger than or equal to 0.');
        }

        $this->container['p_dif_mun'] = $p_dif_mun;

        return $this;
    }

    /**
     * Gets p_dif_cbs
     *
     * @return float
     */
    public function getPDifCbs()
    {
        return $this->container['p_dif_cbs'];
    }

    /**
     * Sets p_dif_cbs
     *
     * @param float $p_dif_cbs Percentual de diferimento para a CBS.
     *
     * @return self
     */
    public function setPDifCbs($p_dif_cbs)
    {
        if (is_null($p_dif_cbs)) {
            array_push($this->openAPINullablesSetToNull, 'p_dif_cbs');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('p_dif_cbs', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($p_dif_cbs) && ($p_dif_cbs < 0)) {
            throw new \InvalidArgumentException('invalid value for $p_dif_cbs when calling RTCInfoTributosDif., must be bigger than or equal to 0.');
        }

        $this->container['p_dif_cbs'] = $p_dif_cbs;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


