<?php
/**
 * RTCListaDoc
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  NuvemFiscal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Nuvem Fiscal
 *
 * API para automação comercial e documentos fiscais.
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.7.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace NuvemFiscal\Model;

use \ArrayAccess;
use \NuvemFiscal\ObjectSerializer;

/**
 * RTCListaDoc Class Doc Comment
 *
 * @category Class
 * @description Grupo relativo aos documentos referenciados nos casos de reembolso, repasse e ressarcimento que serão  considerados na base de cálculo do ISSQN, do IBS e da CBS.
 * @package  NuvemFiscal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RTCListaDoc implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'RTCListaDoc';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'd_fe_nacional' => '\NuvemFiscal\Model\RTCListaDocDFe',
        'doc_fiscal_outro' => '\NuvemFiscal\Model\RTCListaDocFiscalOutro',
        'doc_outro' => '\NuvemFiscal\Model\RTCListaDocOutro',
        'fornec' => '\NuvemFiscal\Model\RTCListaDocFornec',
        'dt_emi_doc' => '\DateTime',
        'dt_comp_doc' => '\DateTime',
        'tp_ree_rep_res' => 'string',
        'x_tp_ree_rep_res' => 'string',
        'vlr_ree_rep_res' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'd_fe_nacional' => null,
        'doc_fiscal_outro' => null,
        'doc_outro' => null,
        'fornec' => null,
        'dt_emi_doc' => 'date',
        'dt_comp_doc' => 'date',
        'tp_ree_rep_res' => null,
        'x_tp_ree_rep_res' => null,
        'vlr_ree_rep_res' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'd_fe_nacional' => false,
        'doc_fiscal_outro' => false,
        'doc_outro' => false,
        'fornec' => false,
        'dt_emi_doc' => true,
        'dt_comp_doc' => true,
        'tp_ree_rep_res' => true,
        'x_tp_ree_rep_res' => true,
        'vlr_ree_rep_res' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'd_fe_nacional' => 'dFeNacional',
        'doc_fiscal_outro' => 'docFiscalOutro',
        'doc_outro' => 'docOutro',
        'fornec' => 'fornec',
        'dt_emi_doc' => 'dtEmiDoc',
        'dt_comp_doc' => 'dtCompDoc',
        'tp_ree_rep_res' => 'tpReeRepRes',
        'x_tp_ree_rep_res' => 'xTpReeRepRes',
        'vlr_ree_rep_res' => 'vlrReeRepRes'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'd_fe_nacional' => 'setDFeNacional',
        'doc_fiscal_outro' => 'setDocFiscalOutro',
        'doc_outro' => 'setDocOutro',
        'fornec' => 'setFornec',
        'dt_emi_doc' => 'setDtEmiDoc',
        'dt_comp_doc' => 'setDtCompDoc',
        'tp_ree_rep_res' => 'setTpReeRepRes',
        'x_tp_ree_rep_res' => 'setXTpReeRepRes',
        'vlr_ree_rep_res' => 'setVlrReeRepRes'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'd_fe_nacional' => 'getDFeNacional',
        'doc_fiscal_outro' => 'getDocFiscalOutro',
        'doc_outro' => 'getDocOutro',
        'fornec' => 'getFornec',
        'dt_emi_doc' => 'getDtEmiDoc',
        'dt_comp_doc' => 'getDtCompDoc',
        'tp_ree_rep_res' => 'getTpReeRepRes',
        'x_tp_ree_rep_res' => 'getXTpReeRepRes',
        'vlr_ree_rep_res' => 'getVlrReeRepRes'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('d_fe_nacional', $data ?? [], null);
        $this->setIfExists('doc_fiscal_outro', $data ?? [], null);
        $this->setIfExists('doc_outro', $data ?? [], null);
        $this->setIfExists('fornec', $data ?? [], null);
        $this->setIfExists('dt_emi_doc', $data ?? [], null);
        $this->setIfExists('dt_comp_doc', $data ?? [], null);
        $this->setIfExists('tp_ree_rep_res', $data ?? [], null);
        $this->setIfExists('x_tp_ree_rep_res', $data ?? [], null);
        $this->setIfExists('vlr_ree_rep_res', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['dt_emi_doc'] === null) {
            $invalidProperties[] = "'dt_emi_doc' can't be null";
        }
        if ($this->container['dt_comp_doc'] === null) {
            $invalidProperties[] = "'dt_comp_doc' can't be null";
        }
        if ($this->container['tp_ree_rep_res'] === null) {
            $invalidProperties[] = "'tp_ree_rep_res' can't be null";
        }
        if (!is_null($this->container['x_tp_ree_rep_res']) && (mb_strlen($this->container['x_tp_ree_rep_res']) > 150)) {
            $invalidProperties[] = "invalid value for 'x_tp_ree_rep_res', the character length must be smaller than or equal to 150.";
        }

        if (!is_null($this->container['x_tp_ree_rep_res']) && (mb_strlen($this->container['x_tp_ree_rep_res']) < 1)) {
            $invalidProperties[] = "invalid value for 'x_tp_ree_rep_res', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['vlr_ree_rep_res'] === null) {
            $invalidProperties[] = "'vlr_ree_rep_res' can't be null";
        }
        if (($this->container['vlr_ree_rep_res'] < 0)) {
            $invalidProperties[] = "invalid value for 'vlr_ree_rep_res', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets d_fe_nacional
     *
     * @return \NuvemFiscal\Model\RTCListaDocDFe|null
     */
    public function getDFeNacional()
    {
        return $this->container['d_fe_nacional'];
    }

    /**
     * Sets d_fe_nacional
     *
     * @param \NuvemFiscal\Model\RTCListaDocDFe|null $d_fe_nacional d_fe_nacional
     *
     * @return self
     */
    public function setDFeNacional($d_fe_nacional)
    {
        if (is_null($d_fe_nacional)) {
            throw new \InvalidArgumentException('non-nullable d_fe_nacional cannot be null');
        }
        $this->container['d_fe_nacional'] = $d_fe_nacional;

        return $this;
    }

    /**
     * Gets doc_fiscal_outro
     *
     * @return \NuvemFiscal\Model\RTCListaDocFiscalOutro|null
     */
    public function getDocFiscalOutro()
    {
        return $this->container['doc_fiscal_outro'];
    }

    /**
     * Sets doc_fiscal_outro
     *
     * @param \NuvemFiscal\Model\RTCListaDocFiscalOutro|null $doc_fiscal_outro doc_fiscal_outro
     *
     * @return self
     */
    public function setDocFiscalOutro($doc_fiscal_outro)
    {
        if (is_null($doc_fiscal_outro)) {
            throw new \InvalidArgumentException('non-nullable doc_fiscal_outro cannot be null');
        }
        $this->container['doc_fiscal_outro'] = $doc_fiscal_outro;

        return $this;
    }

    /**
     * Gets doc_outro
     *
     * @return \NuvemFiscal\Model\RTCListaDocOutro|null
     */
    public function getDocOutro()
    {
        return $this->container['doc_outro'];
    }

    /**
     * Sets doc_outro
     *
     * @param \NuvemFiscal\Model\RTCListaDocOutro|null $doc_outro doc_outro
     *
     * @return self
     */
    public function setDocOutro($doc_outro)
    {
        if (is_null($doc_outro)) {
            throw new \InvalidArgumentException('non-nullable doc_outro cannot be null');
        }
        $this->container['doc_outro'] = $doc_outro;

        return $this;
    }

    /**
     * Gets fornec
     *
     * @return \NuvemFiscal\Model\RTCListaDocFornec|null
     */
    public function getFornec()
    {
        return $this->container['fornec'];
    }

    /**
     * Sets fornec
     *
     * @param \NuvemFiscal\Model\RTCListaDocFornec|null $fornec fornec
     *
     * @return self
     */
    public function setFornec($fornec)
    {
        if (is_null($fornec)) {
            throw new \InvalidArgumentException('non-nullable fornec cannot be null');
        }
        $this->container['fornec'] = $fornec;

        return $this;
    }

    /**
     * Gets dt_emi_doc
     *
     * @return \DateTime
     */
    public function getDtEmiDoc()
    {
        return $this->container['dt_emi_doc'];
    }

    /**
     * Sets dt_emi_doc
     *
     * @param \DateTime $dt_emi_doc Data da emissão do documento dedutível  Ano, mês e dia (AAAA-MM-DD).
     *
     * @return self
     */
    public function setDtEmiDoc($dt_emi_doc)
    {
        if (is_null($dt_emi_doc)) {
            array_push($this->openAPINullablesSetToNull, 'dt_emi_doc');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('dt_emi_doc', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['dt_emi_doc'] = $dt_emi_doc;

        return $this;
    }

    /**
     * Gets dt_comp_doc
     *
     * @return \DateTime
     */
    public function getDtCompDoc()
    {
        return $this->container['dt_comp_doc'];
    }

    /**
     * Sets dt_comp_doc
     *
     * @param \DateTime $dt_comp_doc Data da competência do documento dedutível  Ano, mês e dia (AAAA-MM-DD).
     *
     * @return self
     */
    public function setDtCompDoc($dt_comp_doc)
    {
        if (is_null($dt_comp_doc)) {
            array_push($this->openAPINullablesSetToNull, 'dt_comp_doc');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('dt_comp_doc', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['dt_comp_doc'] = $dt_comp_doc;

        return $this;
    }

    /**
     * Gets tp_ree_rep_res
     *
     * @return string
     */
    public function getTpReeRepRes()
    {
        return $this->container['tp_ree_rep_res'];
    }

    /**
     * Sets tp_ree_rep_res
     *
     * @param string $tp_ree_rep_res Tipo de valor incluído neste documento, recebido por motivo de estarem relacionadas a operações de terceiros,  objeto de reembolso, repasse ou ressarcimento pelo recebedor, já tributados e aqui referenciados.
     *
     * @return self
     */
    public function setTpReeRepRes($tp_ree_rep_res)
    {
        if (is_null($tp_ree_rep_res)) {
            array_push($this->openAPINullablesSetToNull, 'tp_ree_rep_res');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('tp_ree_rep_res', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['tp_ree_rep_res'] = $tp_ree_rep_res;

        return $this;
    }

    /**
     * Gets x_tp_ree_rep_res
     *
     * @return string|null
     */
    public function getXTpReeRepRes()
    {
        return $this->container['x_tp_ree_rep_res'];
    }

    /**
     * Sets x_tp_ree_rep_res
     *
     * @param string|null $x_tp_ree_rep_res Descrição do reembolso ou ressarcimento quando a opção é  \"99 - Outros reembolsos ou ressarcimentos recebidos por valores pagos relativos a operações por conta e ordem de terceiro\".
     *
     * @return self
     */
    public function setXTpReeRepRes($x_tp_ree_rep_res)
    {
        if (is_null($x_tp_ree_rep_res)) {
            array_push($this->openAPINullablesSetToNull, 'x_tp_ree_rep_res');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('x_tp_ree_rep_res', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($x_tp_ree_rep_res) && (mb_strlen($x_tp_ree_rep_res) > 150)) {
            throw new \InvalidArgumentException('invalid length for $x_tp_ree_rep_res when calling RTCListaDoc., must be smaller than or equal to 150.');
        }
        if (!is_null($x_tp_ree_rep_res) && (mb_strlen($x_tp_ree_rep_res) < 1)) {
            throw new \InvalidArgumentException('invalid length for $x_tp_ree_rep_res when calling RTCListaDoc., must be bigger than or equal to 1.');
        }

        $this->container['x_tp_ree_rep_res'] = $x_tp_ree_rep_res;

        return $this;
    }

    /**
     * Gets vlr_ree_rep_res
     *
     * @return float
     */
    public function getVlrReeRepRes()
    {
        return $this->container['vlr_ree_rep_res'];
    }

    /**
     * Sets vlr_ree_rep_res
     *
     * @param float $vlr_ree_rep_res Valor monetário (total ou parcial, conforme documento informado) utilizado para não inclusão na base de cálculo  do ISS e do IBS e da CBS da NFS-e que está sendo emitida (R$).
     *
     * @return self
     */
    public function setVlrReeRepRes($vlr_ree_rep_res)
    {
        if (is_null($vlr_ree_rep_res)) {
            array_push($this->openAPINullablesSetToNull, 'vlr_ree_rep_res');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('vlr_ree_rep_res', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($vlr_ree_rep_res) && ($vlr_ree_rep_res < 0)) {
            throw new \InvalidArgumentException('invalid value for $vlr_ree_rep_res when calling RTCListaDoc., must be bigger than or equal to 0.');
        }

        $this->container['vlr_ree_rep_res'] = $vlr_ree_rep_res;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


